_wandb:
    value:
        cli_version: 0.21.1
        code_path: code/sac.py
        e:
            ftz2hcyoaro4rt4slynevdarcsgpwl3q:
                apple:
                    ecpuCores: 4
                    gpuCores: 8
                    memoryGb: 16
                    name: Apple M1
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                args:
                    - --num_envs
                    - "32"
                    - --track
                codePath: sac.py
                codePathLocal: sac.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "245107195904"
                        used: "210873511936"
                email: daviibuoso@gmail.com
                executable: /Users/davidebuoso/miniforge3/envs/tdp/bin/python
                git:
                    commit: 1785e6e5c5e2fb5ea543a7bdc243d9aabeafa8f9
                    remote: git@github.com:lambdavi/adv_rl.git
                host: MacBookPro.homenet.telecomitalia.it
                memory:
                    total: "17179869184"
                os: macOS-15.5-arm64-arm-64bit
                program: /Users/davidebuoso/Desktop/dev/adv_fail/sac.py
                python: CPython 3.10.16
                root: /Users/davidebuoso/Desktop/dev/adv_fail
                startedAt: "2025-08-28T15:53:36.028759Z"
                writerId: ftz2hcyoaro4rt4slynevdarcsgpwl3q
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
            "4": 3.10.16
            "5": 0.21.1
            "12": 0.21.1
            "13": darwin-arm64
alpha:
    value: 0.2
autotune:
    value: true
batch_size:
    value: 256
buffer_size:
    value: 1000000
capture_video:
    value: false
cuda:
    value: true
env_id:
    value: Hopper-v4
eval_deterministic:
    value: true
eval_episodes:
    value: 10
eval_on_finish:
    value: false
exp_name:
    value: sac
failure_distance_threshold:
    value: 0.5
failure_penalty_weight:
    value: 0.5
gamma:
    value: 0.99
learning_starts:
    value: 5000
max_failure_clusters:
    value: 20
mixed_failure_fraction:
    value: 0.3
num_envs:
    value: 32
policy_frequency:
    value: 2
policy_lr:
    value: 0.0003
q_lr:
    value: 0.001
seed:
    value: 1
target_network_frequency:
    value: 1
tau:
    value: 0.005
torch_deterministic:
    value: true
total_timesteps:
    value: 1000000
track:
    value: true
use_failure_buffer:
    value: false
wandb_entity:
    value: null
wandb_project_name:
    value: cleanRL
